### ISSUE TITLE
Change colour of label

### ISSUE THREAD

**Issue by cbf2020** [giacomomarchioro/PyEnergyDiagrams#16] opened 2022-04-28 15:49 UTC
Can the coloraturas of the text label (bottom text) of each level be changed?

**Comment by cbf2020** [comment] 2022-04-28 15:49
*color

**Comment by giacomomarchioro** [comment] 2022-04-29 06:10
Hi, 
yes using : `diagram.color_bottom_text = 'g'` where 'g' is the matplotlib color.
```
import matplotlib.pyplot as plt
from energydiagram import ED
diagram = ED()
### 
diagram.color_bottom_text = 'g'
####
diagram.add_level(0,'Separated Reactants')
diagram.add_level(-5.4,'mlC1')
diagram.add_level(-15.6,'mlC2','last',) #Using 'last'  or 'l' it will be together with the previous level
diagram.add_level(28.5,'mTS1',color='g')
diagram.add_level(-9.7,'mCARB1')
diagram.add_level(-19.8,'mCARB2','l')
diagram.add_level(20,'mCARBX','last')
```

**Comment by Virginia-White** [comment] 2022-06-14 14:45
Hi,

Is there a way to add an alpha electron without the box? In order to display a spin orbital. When using 
diagram.add_electronbox(level_id=10, **boxes=0**, electrons=1, side=7, spacing_f=10)
it automatically adds a "down electron". 

thank you!

**Comment by giacomomarchioro** [comment] 2022-06-14 19:48
> Hi,
> 
> Is there a way to add an alpha electron without the box? In order to display a spin orbital. When using diagram.add_electronbox(level_id=10, **boxes=0**, electrons=1, side=7, spacing_f=10) it automatically adds a "down electron".
> 
> thank you!

Hi, 
please open a new issue if it is a new issue, the problem is related to making the plot without the box or to the fact that the first electron points down?

**Comment by giacomomarchioro** [comment] 2022-09-15 07:20
Closing this, because the feature was already implemented

**Closed as completed** 2022-09-15 07:19 UTC
